### ISSUE TITLE
HOW TO USE RPLIDAR S2 IN MATLAB?

### ISSUE THREAD

**Issue by ohsekang** [ENSTABretagneRobotics/Hardware-MATLAB#9]
I had used rplidar a1m8 and below code worked well .

now I'm trying to use rplidar s2m1.

rplidar s2 didn't worked in this code and I got result value 1 (value 1 means lidar is not connected with MATLAB)

As I know there are few data about connecting lidar S2M1 to MATLAB.

Do you have any solution about this situation?

hardwarex_init;
pRPLIDAR = CreateRPLIDAR();

% Check and modify the configuration file if needed...
[result] = ConnectRPLIDAR(pRPLIDAR, 'RPLIDAR0.txt')

**Comment by lebarsfa** [comment]
Hello, I don't have the device nor much time to investigate right now. However here are some ideas : 

- If the S2 does not support Standard scan or Express scan modes, things will be probably complicated. Could you share a screenshot similar to https://github.com/ENSTABretagneRobotics/Hardware-MATLAB/issues/3#issuecomment-661101273 showing which scan mode is available in `frame_grabber.exe`? Basically, the discussion in that issue (and related) was what helped to add S1 support so probably a similar debug logic should be applied.
- In https://github.com/ENSTABretagneRobotics/Hardware-MATLAB/blob/master/test_rplidar.m, some comments suggest to set `bStartScanModeAtStartup` to 0 in `RPLIDAR0.txt` and uncomment some lines. It would be interesting to see the return value of the functions at those lines https://github.com/ENSTABretagneRobotics/Hardware-MATLAB/blob/5abc408b51f2e784369493030f921b33ad282a36/test_rplidar.m#L8-L19
- It might be useful to rebuild the necessary things by following https://github.com/ENSTABretagneRobotics/Hardware-MATLAB/tree/master/3rd_support but with the latest version of https://github.com/Slamtec/rplidar_sdk (instead of the mentionned https://github.com/lebarsfa/rplidar_sdk, since https://github.com/Slamtec/rplidar_sdk/blob/feature/release-2.0/docs/ReleaseNote.v2.0.0.md suggests that we need at least the v2.0.0 of the SDK, and possibly Visual Studio 2019). Adaptations might need to be done.

If things get too complicated, another completely different approach (which I never tested, it might be not that simple...) could be to try ROS or ROS2 toolbox, see https://fr.mathworks.com/help/ros/index.html , https://github.com/Slamtec/rplidar_ros , https://fr.mathworks.com/help/ros/ug/work-with-specialized-ros-messages.html#WorkWithSpecializedROSMessagesExample-8 . Here also you might need to determine which version of ROS works with your LIDARs, possibly ROS1 Noetic...
